FROM simulator:intermediate

# Set the working directory to /TreeNN
WORKDIR /TreeNN

# Copy the current directory contents into the container at /TreeNN
COPY . /TreeNN

# To do ifconfig
# RUN apt-get install -y net-tools

# Define environment variable
ENV NAME NODE_ID
ENV NAME NODE_DATA

CMD python3 slave.py -ni $NODE_ID -nd "$NODE_DATA"