delays:
  - src_id: 1
    dest_id: 2
    delay: 0

default_delay: 0
default_mini_batch_size: 100
default_window_interval: 5
default_window_limit: 2
default_epochs_per_window: 1
default_kafka_server: "10.129.2.26:9092"
default_cpus: 0.5
default_memory: "125M"

default_docker_image: "aniketshirke/distributedlearning:simulator"
default_host_test_directory: "~/TrainingData"
default_test_directory: "/TreeNN/data/"

machine:
-   ip: 10.129.2.26   
    username: "synerg"
    password: "synerg"
-   ip: 10.129.26.154
    username: "gise"
    password: "gise123"
-   ip: 10.129.27.164
    username: "giselab"
    password: "giselab123"

nodes:
-   id: 1 
    machine: 0
    port: 8000 
-   id: 2
    machine: 0
    port: 8001
    parent_id: 1
    sensors: [1,2]
-   id: 3
    machine: 0
    port: 8002
    parent_id: 1
    sensors: [3,4]
-   id: 4
    machine: 0
    port: 8003
    parent_id: 1
    sensors: [5,6]
-   id: 5
    machine: 0
    port: 8004
    parent_id: 1
    sensors: [7,8]
-   id: 6
    machine: 0
    port: 8005
    parent_id: 1
    sensors: [9,10]
-   id: 7
    machine: 0
    port: 8006
    parent_id: 1
    sensors: [11,12]
-   id: 8
    machine: 1
    port: 8007
    parent_id: 1
    sensors: [13,14]
-   id: 9
    machine: 1
    port: 8008
    parent_id: 1
    sensors: [15,16]
-   id: 10
    machine: 1
    port: 8009
    parent_id: 1
    sensors: [17,18]
-   id: 11
    machine: 1
    port: 8010
    parent_id: 1
    sensors: [19,20]
-   id: 12
    machine: 1
    port: 8011
    parent_id: 1
    sensors: [21,22]
-   id: 13
    machine: 1
    port: 8012
    parent_id: 1
    sensors: [23,24]
-   id: 14
    machine: 2
    port: 8013
    parent_id: 1
    sensors: [25,26]
-   id: 15
    machine: 2
    port: 8014
    parent_id: 1
    sensors: [27,28]
-   id: 16
    machine: 2
    port: 8015
    parent_id: 1
    sensors: [29,30]
-   id: 17
    machine: 2
    port: 8016
    parent_id: 1
    sensors: [31,32]
-   id: 18
    machine: 2
    port: 8017
    parent_id: 1
    sensors: [33,34]
-   id: 19
    machine: 2
    port: 8018
    parent_id: 1
    sensors: [35,36]
