delays:
  - src_id: 1
    dest_id: 2
    delay: 0

default_delay: 0
default_mini_batch_size: 100
default_window_interval: 5
default_window_limit: 2
default_epochs_per_window: 1
default_kafka_server: "10.152.50.10:9092"

default_cpus: 1
default_memory: "125M"

default_docker_image: "aniketshirke/distributedlearning:simulator"
default_host_test_directory: "~/Simulator/TreeNN/data"
default_test_directory: "/TreeNN/data/"

machine:
-   ip: 10.129.2.26
    username: "synerg"
    password: "synerg"

nodes:
-   id: 1 
    port: 8000 
    machine: 0 
-   id: 2
    port: 8006
    machine: 0
    parent_id: 1
    mini_batch_size: 10
    memory: "125M"
    sensors: [1,2]
   
  
