python3 mnist_sensor.py --sensor-id 50 --source ~/Simulator/mnist_data/train/biased-0.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 51 --source ~/Simulator/mnist_data/train/biased-1.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 52 --source ~/Simulator/mnist_data/train/biased-2.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 53 --source ~/Simulator/mnist_data/train/biased-3.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 54 --source ~/Simulator/mnist_data/train/biased-4.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 55 --source ~/Simulator/mnist_data/train/biased-5.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 56 --source ~/Simulator/mnist_data/train/biased-6.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 57 --source ~/Simulator/mnist_data/train/biased-7.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 50 --source ~/Simulator/mnist_data/train/biased-8.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 57 --source ~/Simulator/mnist_data/train/biased-9.csv -d $1 -k $2 & 
