python3 mnist_sensor.py --sensor-id 0 --source ~/Simulator/mnist_data/train/biased-0.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 1 --source ~/Simulator/mnist_data/train/biased-1.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 2 --source ~/Simulator/mnist_data/train/biased-2.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 3 --source ~/Simulator/mnist_data/train/biased-3.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 4 --source ~/Simulator/mnist_data/train/biased-4.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 5 --source ~/Simulator/mnist_data/train/biased-5.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 6 --source ~/Simulator/mnist_data/train/biased-6.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 7 --source ~/Simulator/mnist_data/train/biased-7.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 8 --source ~/Simulator/mnist_data/train/biased-8.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 9 --source ~/Simulator/mnist_data/train/biased-9.csv -d $1 -k $2 & 
