python3 mnist_sensor.py --sensor-id 40 --source ~/Simulator/mnist_data/train/bigbiased-0.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 41 --source ~/Simulator/mnist_data/train/bigbiased-1.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 42 --source ~/Simulator/mnist_data/train/bigbiased-2.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 43 --source ~/Simulator/mnist_data/train/bigbiased-3.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 40 --source ~/Simulator/mnist_data/train/bigbiased-4.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 41 --source ~/Simulator/mnist_data/train/bigbiased-5.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 42 --source ~/Simulator/mnist_data/train/bigbiased-6.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 43 --source ~/Simulator/mnist_data/train/bigbiased-7.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 40 --source ~/Simulator/mnist_data/train/bigbiased-8.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 41 --source ~/Simulator/mnist_data/train/bigbiased-9.csv -d $1 -k $2 & 
