python3 mnist_sensor.py --sensor-id 20 --source ~/Simulator/mnist_data/train/biased-0.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 21 --source ~/Simulator/mnist_data/train/biased-1.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 22 --source ~/Simulator/mnist_data/train/biased-2.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 23 --source ~/Simulator/mnist_data/train/biased-3.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 24 --source ~/Simulator/mnist_data/train/biased-4.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 20 --source ~/Simulator/mnist_data/train/biased-5.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 21 --source ~/Simulator/mnist_data/train/biased-6.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 22 --source ~/Simulator/mnist_data/train/biased-7.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 23 --source ~/Simulator/mnist_data/train/biased-8.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 24 --source ~/Simulator/mnist_data/train/biased-9.csv -d $1 -k $2 & 
