python3 mnist_sensor.py --sensor-id 30 --source ~/Simulator/mnist_data/train/mediumunbiased-0.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 31 --source ~/Simulator/mnist_data/train/mediumunbiased-1.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 32 --source ~/Simulator/mnist_data/train/mediumunbiased-2.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 33 --source ~/Simulator/mnist_data/train/mediumunbiased-3.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 34 --source ~/Simulator/mnist_data/train/mediumunbiased-4.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 35 --source ~/Simulator/mnist_data/train/mediumunbiased-5.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 36 --source ~/Simulator/mnist_data/train/mediumunbiased-6.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 37 --source ~/Simulator/mnist_data/train/mediumunbiased-7.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 38 --source ~/Simulator/mnist_data/train/mediumunbiased-8.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 39 --source ~/Simulator/mnist_data/train/mediumunbiased-9.csv -d $1 -k $2 & 
