python3 mnist_sensor.py --sensor-id 10 --source ~/Simulator/mnist_data/digits/0.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 11 --source ~/Simulator/mnist_data/digits/1.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 12 --source ~/Simulator/mnist_data/digits/2.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 10 --source ~/Simulator/mnist_data/digits/3.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 11 --source ~/Simulator/mnist_data/digits/4.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 12 --source ~/Simulator/mnist_data/digits/5.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 10 --source ~/Simulator/mnist_data/digits/6.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 11 --source ~/Simulator/mnist_data/digits/7.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 12 --source ~/Simulator/mnist_data/digits/8.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 10 --source ~/Simulator/mnist_data/digits/9.csv -d $1 -k $2 & 
