python3 mnist_sensor.py --sensor-id 10 --source ~/Simulator/mnist_data/train/unbiased-0.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 11 --source ~/Simulator/mnist_data/train/unbiased-1.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 12 --source ~/Simulator/mnist_data/train/unbiased-2.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 10 --source ~/Simulator/mnist_data/train/unbiased-3.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 11 --source ~/Simulator/mnist_data/train/unbiased-4.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 12 --source ~/Simulator/mnist_data/train/unbiased-5.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 10 --source ~/Simulator/mnist_data/train/unbiased-6.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 11 --source ~/Simulator/mnist_data/train/unbiased-7.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 12 --source ~/Simulator/mnist_data/train/unbiased-8.csv -d $1 -k $2 & 
python3 mnist_sensor.py --sensor-id 10 --source ~/Simulator/mnist_data/train/unbiased-9.csv -d $1 -k $2 & 
