delays:
  - src_id: 1
    dest_id: 2
    delay: 0

default_delay: 0
default_mini_batch_size: 100
default_window_interval: 5
default_window_limit: 2
default_epochs_per_window: 1
default_kafka_server: "192.168.43.18:9092"
default_cpus: 0.25
default_memory: "100M"

default_docker_image: "aniketshirke/distributedlearning:simulator"
default_host_test_directory: "~/Simulator/TreeNN/data"

nodes:
-   id: 1 
    ip: 192.168.43.18
    port: 8000 
    test_directory: "/TreeNN/data/"
    username: "aniket"
    password: "08081997ani"
-   id: 2
    ip: 192.168.43.18
    port: 8006
    parent_id: 1
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 3
    ip: 192.168.43.18
    port: 8007
    parent_id: 1
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 4
    ip: 192.168.43.18
    port: 8008
    parent_id: 1
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 5
    ip: 192.168.43.18
    port: 8008
    parent_id: 2
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 6
    ip: 192.168.43.18
    port: 8008
    parent_id: 2
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 7
    ip: 192.168.43.18
    port: 8008
    parent_id: 2
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 8
    ip: 192.168.43.18
    port: 8008
    parent_id: 3
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 9
    ip: 192.168.43.18
    port: 8008
    parent_id: 3
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 10
    ip: 192.168.43.18
    port: 8008
    parent_id: 3
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 11
    ip: 192.168.43.18
    port: 8008
    parent_id: 4
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 12
    ip: 192.168.43.18
    port: 8008
    parent_id: 4
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 13
    ip: 192.168.43.18
    port: 8008
    parent_id: 4
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"  
-   id: 14
    ip: 192.168.43.18
    port: 8008
    parent_id: 5
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 15
    ip: 192.168.43.18
    port: 8008
    parent_id: 5
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 16
    ip: 192.168.43.18
    port: 8008
    parent_id: 6
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 17
    ip: 192.168.43.18
    port: 8008
    parent_id: 6
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 18
    ip: 192.168.43.18
    port: 8008
    parent_id: 7
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 19
    ip: 192.168.43.18
    port: 8008
    parent_id: 7
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 20
    ip: 192.168.43.18
    port: 8008
    parent_id: 8
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 21
    ip: 192.168.43.18
    port: 8008
    parent_id: 8
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 22
    ip: 192.168.43.18
    port: 8008
    parent_id: 9
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 23
    ip: 192.168.43.18
    port: 8008
    parent_id: 9
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 24
    ip: 192.168.43.18
    port: 8008
    parent_id: 10
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 25
    ip: 192.168.43.18
    port: 8008
    parent_id: 10
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 26
    ip: 192.168.43.18
    port: 8008
    parent_id: 11
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 27
    ip: 192.168.43.18
    port: 8008
    parent_id: 11
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 28
    ip: 192.168.43.18
    port: 8008
    parent_id: 12
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 29
    ip: 192.168.43.18
    port: 8008
    parent_id: 12
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 30
    ip: 192.168.43.18
    port: 8008
    parent_id: 13
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
-   id: 31
    ip: 192.168.43.18
    port: 8008
    parent_id: 13
    test_directory: "/TreeNN/data/"
    mini_batch_size: 10
    username: "aniket"
    password: "08081997ani"
    memory: "125M"
