# delay should be in milliseconds
delays:
  - src_id: 1
    dest_id: 2
    delay: 0

# Default network delay (in ms) between the nodes
default_delay: 0

default_mini_batch_size: 100
default_window_interval: 5
default_window_limit: 2
default_epochs_per_window: 1


# Mention the list of all nodes (VMs)
# 10.129.2.21 address of vm1 for setup1 , it contains 5 worker nodes
# IP: 10.129.2.29 address of vms for setup2, it conatins 3 parameter server and 1 worker node 
nodes:
  - id: 1 # The unique ID for the node
    ip: 10.129.2.21 # The IP address on which its RPC server is to be run
    port: 8000 # The port on which its RPC server is to be run
    file_name: "data/Cluster7_Data.csv"
    username: "synerg"
    password: "synerg"
  
  - id: 7
    ip: 10.129.2.21
    port: 8006
    parent_id: 1
    push_interval: 1 # Default properties mentioned above can be customized for each node
    file_name: "data/Cluster1_Data.csv" # unlabelled data
    username: "synerg"
    password: "synerg"
  
  - id: 8
    ip: 10.129.2.21
    port: 8007
    parent_id: 1
    push_interval: 1 # Default properties mentioned above can be customized for each node
    file_name: "data/Cluster2_Data.csv" # unlabelled data
    username: "synerg"
    password: "synerg"
    
  - id: 9
    ip: 10.129.2.21
    port: 8008
    parent_id: 1
    push_interval: 1 # Default properties mentioned above can be customized for each node
    file_name: "data/Cluster6_Data.csv" # unlabelled data
    username: "synerg"
    password: "synerg"
   
  
  
