## Bandwidth available to nodes
bandwidths:
  - src_id: 1
    dest_id: 2
    bandwidth: 1000000

default_bandwidth: 1000000

## Data streaming info
default_window_interval: 20
default_window_limit: 100
default_kafka_server: "10.129.2.26:9092"
default_test_directory: "/TreeNN/data/"

## Docker specific fields
default_cpus: 0.8
default_memory: "400M"
default_docker_image: "aniketshirke/distributedlearning:simulator"
default_host_test_directory: "~/Simulator/mnist_data/test"
default_policy: 0
default_args: 0

## Machine info
machine:
-   ip: 10.129.26.111
    username: "ub"
    password: "spark!sfun"

## arguments to be passed to the learning model
application_arguments:
-   model             : 'MNIST'
    input_size        : 784
    output_size       : 10
    num_hidden_layers : 3
    hidden_layer_sizes: [20,10,10]
    alpha             : 0.1
    batch_size        : 20
    epochs            : 10

## Policy for sharing models
policy:
-   type: 'SimplePolicy'
    args: 
-   type: 'TimePolicy'
    args:
        push_interval: 10
        pull_interval: 10
-   type: 'WindowPolicy'
    args:
        push_count: 1
        pull_count: 400
-   type: 'AccuracyPolicy'
    args:
        threshold: 2

nodes:
-   id: 1 
    port: 8050
    machine: 0 
-   id: 2
    port: 8051
    machine: 0
    parent_id: 1
-   id: 3
    port: 8052
    machine: 0
    parent_id: 1
-   id: 4
    port: 8053
    machine: 0
    parent_id: 2
-   id: 5
    port: 8054
    machine: 0
    parent_id: 2
-   id: 6
    port: 8055
    machine: 0
    parent_id: 3
-   id: 7
    port: 8056
    machine: 0
    parent_id: 3
-   id: 8 
    port: 8057
    machine: 0 
    parent_id: 4
    sensors: [50]
-   id: 9
    port: 8058
    machine: 0
    parent_id: 4
    sensors: [51]
-   id: 10
    port: 8059
    machine: 0
    parent_id: 5
    sensors: [52]
-   id: 11
    port: 8060
    machine: 0
    parent_id: 5
    sensors: [53]
-   id: 12
    port: 8061
    machine: 0
    parent_id: 6
    sensors: [54]
-   id: 13
    port: 8062
    machine: 0
    parent_id: 6
    sensors: [55]
-   id: 14
    port: 8063
    machine: 0
    parent_id: 7
    sensors: [56]
-   id: 15
    port: 8064
    machine: 0
    parent_id: 7
    sensors: [57]


cloud:
    machine: 0
    port: 9050
    cpus: 2
    memory: "500M" 
