delays:
  - src_id: 1
    dest_id: 2
    delay: 0

default_delay: 0
default_mini_batch_size: 10
default_window_interval: 10
default_window_limit: 500
default_epochs_per_window: 5
default_kafka_server: "10.129.2.26:9092"

default_cpus: 0.7
default_memory: "500M"

default_docker_image: "aniketshirke/distributedlearning:simulator"
default_host_test_directory: "~/Simulator/TreeNN/data"
default_test_directory: "/TreeNN/data/"

machine:
-   ip: 10.129.2.26
    username: "synerg"
    password: "synerg"

nodes:
-   id: 1
    port: 8000
    machine: 0
-   id: 2
    port: 8006
    machine: 0
    parent_id: 1
-   id: 3
    port: 8007
    machine: 0
    parent_id: 1
-   id: 4
    port: 8008
    machine: 0
    parent_id: 2
    sensors: [1]
-   id: 5
    port: 8009
    machine: 0
    parent_id: 2
    sensors: [2]
-   id: 6
    port: 8010
    machine: 0
    parent_id: 3
    sensors: [3]
-   id: 7
    port: 8011
    machine: 0
    parent_id: 3
    sensors: [4]
